/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JpgToPdfRouteImport } from './routes/jpg-to-pdf'
import { Route as PngToPdfRouteImport } from './routes/png-to-pdf'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WebpToPdfRouteImport } from './routes/webp-to-pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JpgToPdfRoute = JpgToPdfRouteImport.update({
  id: '/jpg-to-pdf',
  path: '/jpg-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PngToPdfRoute = PngToPdfRouteImport.update({
  id: '/png-to-pdf',
  path: '/png-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WebpToPdfRoute = WebpToPdfRouteImport.update({
  id: '/webp-to-pdf',
  path: '/webp-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jpg-to-pdf': typeof JpgToPdfRoute
  '/png-to-pdf': typeof PngToPdfRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/webp-to-pdf': typeof WebpToPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jpg-to-pdf': typeof JpgToPdfRoute
  '/png-to-pdf': typeof PngToPdfRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/webp-to-pdf': typeof WebpToPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jpg-to-pdf': typeof JpgToPdfRoute
  '/png-to-pdf': typeof PngToPdfRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/webp-to-pdf': typeof WebpToPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/jpg-to-pdf' | '/png-to-pdf' | '/sitemap.xml' | '/webp-to-pdf'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jpg-to-pdf' | '/png-to-pdf' | '/sitemap.xml' | '/webp-to-pdf'
  id:
    | '__root__'
    | '/'
    | '/jpg-to-pdf'
    | '/png-to-pdf'
    | '/sitemap.xml'
    | '/webp-to-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JpgToPdfRoute: typeof JpgToPdfRoute
  PngToPdfRoute: typeof PngToPdfRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WebpToPdfRoute: typeof WebpToPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jpg-to-pdf': {
      id: '/jpg-to-pdf'
      path: '/jpg-to-pdf'
      fullPath: '/jpg-to-pdf'
      preLoaderRoute: typeof JpgToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/png-to-pdf': {
      id: '/png-to-pdf'
      path: '/png-to-pdf'
      fullPath: '/png-to-pdf'
      preLoaderRoute: typeof PngToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webp-to-pdf': {
      id: '/webp-to-pdf'
      path: '/webp-to-pdf'
      fullPath: '/webp-to-pdf'
      preLoaderRoute: typeof WebpToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JpgToPdfRoute: JpgToPdfRoute,
  PngToPdfRoute: PngToPdfRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WebpToPdfRoute: WebpToPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
